name: Backend-Deploy
on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    types: [opened, reopened]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        run: cd backend && npm run deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}